version: '3'

services:

  mariadb:
    build: ./mariadb
    container_name: mariadb
    ports:
      - "3306:3306"
    environment:
      MARIADB_ROOT_PASSWORD: root
    volumes:
      - $HOME/developer/weddingDB:/var/lib/mysql
    networks:
      - isolation-network

  wordpress:
    build: ./wordpress
    container_name: wordpress
    ports:
    - "80:80"
    - "9000:9000"
    links:
      - mariadb:mysql
    environment:
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: root
      WORDPRESS_DB_NAME: dbs12561842
      WORDPRESS_TABLE_PREFIX: io7g_
      WORDPRESS_DEBUG: 1
    volumes:
      - $HOME/projects/erytheiaNet/bodaWeb/myWedding/:/var/www/html/wp-content/themes/myWedding/
    networks:
      - isolation-network

networks:
  isolation-network:
    driver: bridge
